# Generated by Django 3.1.1 on 2020-11-01 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_auto_20201031_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technologiesandframework',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='work.service'),
        ),
    ]
