# Generated by Django 3.1.1 on 2020-11-02 16:43

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_auto_20201101_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='technologiesandframework',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
