# Generated by Django 3.1.1 on 2020-09-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('about_Developer_text', models.TextField()),
                ('developer_background_img', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
