# Generated by Django 3.1.1 on 2020-09-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20200913_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('percentage', models.IntegerField(max_length=100)),
                ('bar_color', models.CharField(max_length=10)),
            ],
        ),
    ]
