# Generated by Django 3.1.1 on 2020-09-17 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_auto_20200917_1857'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Technology',
        ),
    ]
