# Generated by Django 3.1.1 on 2020-10-14 16:36

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_delete_technology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='about_developer_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
