# Generated by Django 3.1.1 on 2020-10-14 16:37

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_auto_20201014_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
